type: code
files:
- name: main.py
  visible: true
  learner_created: false
feedback_link: https://hyperskill.org/learn/step/9149#comment
status: Failed
feedback:
  message: |
    Failed test #1 of 5. Runtime error

    This is a sample test from the problem statement!

    Test input:
    Paws 11
    Kittens 9
    MEOW
    Correct output:
    Paws

    Your code output:


    Error:
    Traceback (most recent call last):
      File "jailed_code", line 2, in <module>
        dict(cafes)
    ValueError: dictionary update sequence element #0 has length 4; 2 is required
  time: "Wed, 21 Sep 2022 13:22:42 UTC"
record: -1
